# Copyright (C) 2022-2023 Catena-X Association and others. 
# 
# This program and the accompanying materials are made available under the
# terms of the Apache License 2.0 which is available at
# http://www.apache.org/licenses/.
# 
# SPDX-FileType: SOURCE
# SPDX-FileCopyrightText: 2022-2023 Catena-X Association
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.agent.endpoints.default.port }}
      targetPort: default
      protocol: TCP
      name: default
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
