# Copyright (C) 2022-2023 Catena-X Association and others. 
# 
# This program and the accompanying materials are made available under the
# terms of the Apache License 2.0 which is available at
# http://www.apache.org/licenses/.
# 
# SPDX-FileType: SOURCE
# SPDX-FileCopyrightText: 2022-2023 Catena-X Association
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  portal.toml: |-
  {{- .Files.Get "resources/portal.toml" | nindent 4 }}
  
  {{- $scope := . }}
  {{- range $asset, $file := .Values.ontologies }}
  {{ $asset }}: |-
  {{- $scope.Files.Get $file | nindent 4 }}
  {{- end }}
  {{- range $endpoint, $binding := .Values.bindings }}
  {{ $endpoint }}.obda: |-
  {{- $binding.mapping | nindent 4 }}
  {{ $endpoint }}.properties: |-
  {{- range $skey, $svalue := $binding.settings }}
    {{ $skey }}: {{ $svalue }}
  {{- end }}
  {{- end }}

