# Copyright (C) 2022-2023 Catena-X Association and others. 
# 
# This program and the accompanying materials are made available under the
# terms of the Apache License 2.0 which is available at
# http://www.apache.org/licenses/.
# 
# SPDX-FileType: SOURCE
# SPDX-FileCopyrightText: 2022-2023 Catena-X Association
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
